### ISSUE TITLE
unicorn.ninja

### ISSUE THREAD

**Issue by es128** [sindresorhus/is-public-domain#1]
https://www.name.com/domain/search-2-3/?domain=unicorn&tld=ninja

Available, but so expensive!

Just FYI. Maybe you'd want to buy it anyway, or something.

![image](https://cloud.githubusercontent.com/assets/1740641/9440390/bd0c753a-4a3c-11e5-9d02-ae69d1fe0d9e.png)

**Comment by sindresorhus** [comment]
I know, but too expensive...
